name: Build and deploy Python app to Azure Web App - deepseekweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Requerido para actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List repository files
        run: ls -R  # Muestra la estructura de archivos y carpetas para depuración

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          cd App  # Cambiar a la carpeta correcta
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd App
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd App
          zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: App/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Requerido para autenticación con Azure
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F00D9A1BC28A4314929C1A84F65EDBA4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B030DEED100649E585D017558F44B9C2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D50D93DA8B5F4B56BB12ADC694782EEA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'deepseekweb'
          slot-name: 'Production'
