name: Build and deploy Python app to Azure Web App - deepseekweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd app  # 📌 Entrar en la carpeta antes de instalar
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd app  # 📌 Asegurar que se empaqueta desde la carpeta correcta
          zip -r ../release.zip .  # Subir solo el contenido de `app/`
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app  # 📌 Extraer todo en `app/`

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'deepseekweb'
          slot-name: 'Production'

      - name: Extract deployment files
        run: |
          cd /home/site/wwwroot/
          if [ -f output.tar.gz ]; then tar -xvzf output.tar.gz; fi
          if [ -f release.zip ]; then unzip -o release.zip; fi
          chmod +x startup.sh
          ./startup.sh
